baseURL = 'https://taintedabomination.github.io/'
languageCode = 'cs'
title = 'taintedabomination'

[params]
titlePostfix = " | taintedabomination"
license = "GNU GPLv3"
licenseLink = "https://www.gnu.org/licenses/gpl-3.0.html"
